# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

url: https://benbrooklakeshore.org

# Site settings
title: BLNA
email: your-email@domain.com
description: "BLNA is a non-profit organization with a sole purpose to preserve and improve the surrounding neighborhoods."


# Team names, titles and social links
people:
- name: Rick Radford
  pic: 1
  position: President

- name: James Staud
  pic: 2
  position: Vice President

- name: Susan Swisher
  pic: 3
  position: Secretary

- name: Lisa Bradberry
  pic: 4
  position: Treasurer

- name: Adam Driggers
  pic: 5
  position: Board Member

- name: Bruce Southey
  pic: 6
  position: Board Member, Safety and Security Member

- name: Skip Madara
  pic: 3
  position: Board Member and CC Building Manager

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/BLNAus/

# Postal address (add as many lines as necessary)
address:
  - line: 6108 Tiger Trail
  - line: Fort Worth, TX 76126

# Build settings
markdown: kramdown
permalink: pretty

# Build settings
theme: jekyll-agency
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
